### ISSUE TITLE
Required changes for the next update

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/wrims-checklist#16]
Before we go to the publication of WRIMS on GBIF, some adjustements in the dataset are required. 
I here provide an final overview of all Darwin Core terms in the export, whether they are OK or whether adjustments are required for the next update. When changes are needed, I refer to the specific issue (and comment) to provide more details. 

@bart-v, please integrate these changes and tick off the boxes next the terms below, so that I can track whether or not all suggestions were integrated. 

RECORD LEVEL TERMS

- [x] modified
- [x] language: `en` see meta.xml
- [x] license: CC-BY, see meta.xml
- [x] rightsHolder: `WoRMS Editorial board`, see meta.xml
- [x] bibliographicCitation
- [x] references	
- [x] datasetID: to be completed after publication on GBIF
- [x] institutionCode: VLIZ?
- [x] datasetName: WoRMS WRIMS

TAXON CORE

- [x] taxonID: integrate aphiaID, see [issue 5](https://github.com/trias-project/wrims-checklist/issues/5)
- [x] scientificNameID
- [x] acceptedNameUsageID: integrate aphiaID? see [issue 14](https://github.com/trias-project/wrims-checklist/issues/14)
- [x] parentNameUsageID: integrate aphiaID? see [issue 14](https://github.com/trias-project/wrims-checklist/issues/14)
- [x] namePublishedInID: suggestions is to integrate the full DOI see [issue 15](https://github.com/trias-project/wrims-checklist/issues/15)
- [x] scientificName: see [issue 7](https://github.com/trias-project/wrims-checklist/issues/7)
- [x] acceptedNameUsage
- [x] parentNameUsage
- [x] namePublishedIn
- [x] nameAccordingTo
- [x] namePublishedInYear
- [x] kingdom (one kingdom lacking, urn:lsid:marinespecies.org:taxname:662648, error?)
- [x] phylum
- [x] class
- [x] order
- [x] family
- [x] genus
- [x] subgenus
- [x] specificEpithet
- [x] infraspecificEpithet
- [x] taxonRank: see [issue 8](https://github.com/trias-project/wrims-checklist/issues/8)
- [x] scientificNameAuthorship
- [x] nomenclaturalCode
- [x] taxonomicStatus: split up information in `taxonomicStatus` and `nomenclaturalStatus`. see [issue 9](https://github.com/trias-project/wrims-checklist/issues/9). Specific details for the mapping are provided in [this comment](https://github.com/trias-project/wrims-checklist/issues/9#issuecomment-459768273)

DISTRIBUTION EXTENSION

- [x] taxonID: integrate aphiaID, see [issue 5](https://github.com/trias-project/wrims-checklist/issues/5)
- [x] locationID
- [x] locality
- [x] countryCode: to be implemented, see [issue 11](https://github.com/trias-project/wrims-checklist/issues/11)
- [ ] occurrenceStatus: map to suggested vocabulary, see [issue 2](https://github.com/trias-project/wrims-checklist/issues/2). For specific details for the mapping, see [this comment](https://github.com/trias-project/wrims-checklist/issues/2#issuecomment-470138342)
- [ ] establishmentMeans: map to suggested vocabulary, see [issue 2](https://github.com/trias-project/wrims-checklist/issues/2). For specific details for the mapping, see [this comment](https://github.com/trias-project/wrims-checklist/issues/2#issuecomment-470138342)
- [ ] invasiveness: not a DwC term. Integrate this in the description extension and follow term mapping as specified in [issue 2](https://github.com/trias-project/wrims-checklist/issues/2). For specific details for the mapping, see [this comment](https://github.com/trias-project/wrims-checklist/issues/2#issuecomment-470138342)
- [x] eventDate: generate from `startDayOfYear` and `endDayOfYear`, see [issue 12](https://github.com/trias-project/wrims-checklist/issues/12)
- [x] source
- [x] occurrenceRemarks

SPECIES PROFILE EXTENSION

- [x] taxonID: integrate aphiaID, see [issue 5](https://github.com/trias-project/wrims-checklist/issues/5)
- [x] isMarine
- [x] isFreshwater
- [x] isTerrestrial
- [x] isExtinct

VERNACULAR NAME
- [x] taxonID: integrate aphiaID, see [issue 5](https://github.com/trias-project/wrims-checklist/issues/5)
- [x] vernacularName
- [x] source
- [x] language

LITERATURE REFERENCES
- [x] taxonID: integrate aphiaID, see [issue 5](https://github.com/trias-project/wrims-checklist/issues/5)
- [x] identifier
- [x] bibliographicCitation
- [x] title
- [x] creator
- [x] date
- [x] description
- [x] type

DESCRIPTION EXTENSION - see comment below

- [x] taxonID: integrate aphiaID, see [issue 5](https://github.com/trias-project/wrims-checklist/issues/5)
- [x] description
- [x] type: pathway, invasion stage
- [x] source

**Comment by LienReyserhove** [comment]
The structure of the description extension is slightly different from the other extensions. 

Structure of `taxon core`, `distribution`, `species profile`, `vernacular name` and `literature reference` extension:

taxonID | variable 1 | variable 2
--- | --- | ---
UID1 | x | a
UID2 | y | b

Structure of `description `extension:

taxonID | description | type
--- | --- | ---
UID1 | x | variable 1
UID1 | a | variable 2
UID2 | y | variable 1
UID2 | b | variable 2

The following information should be included in the description extension:
- pathway (see [issue 13](https://github.com/trias-project/wrims-checklist/issues/13))
- invasion stage (see [issue 2](https://github.com/trias-project/wrims-checklist/issues/2#issuecomment-470138342))

In the case of WRiMS, the description extension should look like this:

taxonID | description | type
--- | --- | ---
aphiaID1 | biocontrol | pathway
aphiaID1 | fisheries | pathway
aphiaID1 | established | invasion stage
aphiaID2 | plant introductions | pathway
... |... | ...

**Comment by bart-v** [comment]
1.  I can't do anything in this repo, so I can't tick off things...
2. description extension has been implemented and will be available in the next export (2019-04-01)

**Comment by LienReyserhove** [comment]
I went through the latest export and most of the pending issues have been resolved, many thanks for that.
A few issues remain unsolved:

1.`taxonomicStatus` and `nomenclaturalstatus` https://github.com/trias-project/wrims-checklist/issues/9
2. `occurrenceStatus`, `establishmentMeans` and `Invasion stage` #2 
3. Mapping of description extension #17

Could you please respond to the specific issues in case you don't agree with the suggested changes or integrate the comments in the next export?
